config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views import defaults as default_views
from django.views.decorators.csrf import ensure_csrf_cookie
from visualisation.views import visualisation_tree_view


@ensure_csrf_cookie
@login_required
def index(request):
    return visualisation_tree_view(request)


urlpatterns = [
    path("", index, name='index'),
    path('map/', include('map.urls')),
    path('diagram/', include('diagram.urls')),
    path('data/', include('data.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

router-map/account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

router-map/data/urls.py
from django.urls import path

from . import views

app_name = 'data'
urlpatterns = [
    path('last_update_time', views.last_update_time, name='last_update_time'),
    path('device/<int:pk>/', views.DeviceDetailView.as_view(), name='device_detail'),
    path('connection/<connection_id>/', views.ConnectionView.as_view(), name='connection_detail'),
    path('connection/<connection_id>/delete', views.delete_inactive_links, name='connection_inactive_delete'),
    path('manage_devices', views.manage_devices, name='manage_devices'),
]

router-map/diagram/urls.py
from django.urls import path

from . import views

app_name = 'diagram'
urlpatterns = [
    path("<diagram_pk>/", views.index, name='index'),
    path("<diagram_pk>/graph.json", views.graph, name='graph'),
    path('<diagram_pk>/inactive_connections', views.InactiveView.as_view(), name='inactive_connections'),
    path('<diagram_pk>/update_positions', views.update_positions, name='update_positions'),
    path('new', views.update, name='create'),
    path('<diagram_pk>/update', views.update, name='update'),
    path('<diagram_pk>/manage_devices', views.manage_devices, name='manage_devices'),
    path('<diagram_pk>/add_devices_via_csv', views.add_devices_via_csv, name='add_devices_via_csv'),
]

router-map/map/urls.py
from django.urls import path

from . import views

app_name = 'map'
urlpatterns = [
    path('<map_pk>/', views.index, name='index'),
    path('<map_pk>/points.json', views.points, name='points'),
    path('<map_pk>/lines.json', views.lines, name='lines'),
    path('<map_pk>/inactive_connections', views.InactiveView.as_view(), name='inactive_connections'),
    path("<map_pk>/view_settings", views.view_settings, name='view_settings'),
    path('new', views.update, name='create'),
    path('<map_pk>/update', views.update, name='update'),
    path('<map_pk>/manage_devices', views.manage_devices, name='manage_devices'),
    path('<map_pk>/add_devices_via_csv', views.add_devices_via_csv, name='add_devices_via_csv'),
]

router-map/data/models.py
from django.contrib.gis.db import models

from utils.managers import GetOrNoneManager


class Device(models.Model):
    CONNECTION_TYPES = (
        ('snmp', 'snmp'),
        ('netconf', 'netconf'),
    )

    id = models.AutoField(primary_key=True)
    name = models.CharField(default='', max_length=127, blank=True)
    ip_address = models.GenericIPAddressField()
    chassis_id = models.CharField(default='', max_length=31, blank=True)
    snmp_community = models.CharField(default='', max_length=255, blank=True,
                                      help_text='string used to authenticate SNMP queries')
    connection_is_active = models.BooleanField(default=False)
    connection_type = models.CharField(max_length=15, choices=CONNECTION_TYPES, default='snmp')

    def __str__(self):
        return f"{self.name} (id: {self.id})"


class Interface(models.Model):
    device = models.ForeignKey('Device', on_delete=models.CASCADE)
    number = models.IntegerField(help_text='number used to identify interface in MIB')
    name = models.CharField(default='', max_length=127, blank=True)
    speed = models.IntegerField(default=0)
    aggregate_interface = models.ForeignKey('Interface', null=True, on_delete=models.SET_NULL, related_name='aggregate')
    active = models.BooleanField(default=True)
    objects = GetOrNoneManager()


class Link(models.Model):
    local_interface = models.ForeignKey('Interface', on_delete=models.CASCADE, related_name='local_interface',
                                        null=True)
    remote_interface = models.ForeignKey('Interface', on_delete=models.CASCADE, null=True)
    active = models.BooleanField(default=True)

router-map/diagram/models.py
from django.contrib.gis.db import models

from data.models import Device
from visualisation.models import Visualisation


class Diagram(Visualisation):
    devices = models.ManyToManyField(Device, through='DeviceDiagramRelationship')


class DeviceDiagramRelationship(models.Model):
    diagram = models.ForeignKey(Diagram, on_delete=models.CASCADE)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    device_position_x = models.IntegerField(default=None, null=True)
    device_position_y = models.IntegerField(default=None, null=True)

router-map/map/models.py
from django.contrib.gis.db import models

from data.models import Device
from visualisation.models import Visualisation


class Map(Visualisation):
    devices = models.ManyToManyField(Device, through='DeviceMapRelationship')


class DeviceMapRelationship(models.Model):
    map = models.ForeignKey(Map, on_delete=models.CASCADE)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    point = models.PointField(default=None, null=True)

router-map/data/forms.py
from crispy_forms.helper import FormHelper
from django.forms import modelformset_factory, ModelForm

from data.models import Device


class DeviceForm(ModelForm):
    class Meta:
        model = Device
        fields = ['name', 'ip_address', 'connection_type', 'snmp_community']
        help_texts = {
            'snmp_community': None,
        }


class DeviceFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(DeviceFormSetHelper, self).__init__(*args, **kwargs)
        self.form_tag = False
        self.template = 'bootstrap4/table_inline_formset.html'


DeviceFormSet = modelformset_factory(Device, form=DeviceForm, extra=0, can_delete=True, min_num=1)

router-map/diagram/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from django.core.validators import FileExtensionValidator
from django.forms import ModelForm, modelformset_factory

from diagram.models import Diagram, DeviceDiagramRelationship
from utils.formsets import UniqueDeviceFormSet
from visualisation.views import get_visualisation_layout


class DiagramAddDevicesCsv(forms.Form):
    devices = forms.FileField(label='Add new devices',
                              help_text="Csv file with new device list. "
                                        "Every line describes one device and contains the following fields "
                                        "separated by comma: name, ip address, connection type (snmp/netconf), "
                                        "snmp community(empty if not requested), position x, position y "
                                        "(position defined in pixels); "
                                        "for example: router_1,10.234.149.1,snmp,read,150,200",
                              validators=[FileExtensionValidator(['csv'])])

    def __init__(self, *args, **kwargs):
        super(DiagramAddDevicesCsv, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_show_labels = False


class DiagramForm(forms.ModelForm):
    class Meta:
        model = Diagram
        fields = ['name', 'display_link_descriptions', 'links_default_width', 'highlighted_links_width',
                  'highlighted_links_range_min', 'highlighted_links_range_max', 'parent']

    def __init__(self, *args, **kwargs):
        super(DiagramForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = get_visualisation_layout()


class DiagramFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(DiagramFormSetHelper, self).__init__(*args, **kwargs)
        self.form_tag = False
        self.template = 'bootstrap4/table_inline_formset.html'


class DeviceDiagramRelationshipForm(ModelForm):
    class Meta:
        model = DeviceDiagramRelationship
        fields = ['device', 'device_position_x', 'device_position_y']

    def __init__(self, *arg, **kwarg):
        super(DeviceDiagramRelationshipForm, self).__init__(*arg, **kwarg)
        self.empty_permitted = False


DiagramFormSet = modelformset_factory(DeviceDiagramRelationship, form=DeviceDiagramRelationshipForm,
                                      extra=0, can_delete=True, formset=UniqueDeviceFormSet, min_num=1)

router-map/account/views.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'username',
            'password',
            FormActions(
                Submit('submit', 'Log in'),
            )
        )


class LoginView(auth_views.LoginView):
    template_name = 'login.html'
    authentication_form = LoginForm

router-map/data/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.views.generic import DetailView, TemplateView

from data.forms import DeviceFormSetHelper, DeviceFormSet
from data.models import Device, Link
from data.redis_client import redis_client


@login_required
def last_update_time(request):
    time = redis_client.get_last_update_time()
    if time is None:
        return HttpResponse()
    else:
        return HttpResponse(time)


class DeviceDetailView(LoginRequiredMixin, DetailView):
    model = Device
    template_name = 'device_detail.html'


class ConnectionView(LoginRequiredMixin, TemplateView):
    template_name = 'connection_detail.html'

    def get_context_data(self, **kwargs):
        link_pk_list = [int(x) for x in kwargs['connection_id'].split('_')]
        links = Link.objects.filter(pk__in=link_pk_list)
        if not links.exists():
            raise Http404("The requested resource was not found on this server.")
        number_of_active_links = links.filter(active=True).count()
        last_link = links.last()
        speed = last_link.local_interface.speed
        connection = {
            "device1": last_link.local_interface.device.name,
            "device2": last_link.remote_interface.device.name,
            "number_of_links": links.count(),
            "number_of_active_links": number_of_active_links,
            "speed": speed,
            "interface1": last_link.local_interface.name
            if last_link.local_interface.aggregate_interface is None
            else last_link.local_interface.aggregate_interface.name,
            "interface2": last_link.remote_interface.name
            if last_link.remote_interface.aggregate_interface is None
            else last_link.remote_interface.aggregate_interface.name,
        }
        context = super().get_context_data(**kwargs)
        context['connection'] = connection
        return context


@require_POST
@login_required
@permission_required('data.delete_link', raise_exception=True)
def delete_inactive_links(request, connection_id):
    link_pk_list = [int(x) for x in connection_id.split('_')]
    links = Link.objects.filter(pk__in=link_pk_list)
    if not links.exists():
        raise Http404("The requested resource was not found on this server.")
    inactive_links = links.filter(active=False)
    inactive_links.delete()
    return HttpResponse()


@login_required
@permission_required(['data.add_device', 'data.change_device', 'data.delete_device'], raise_exception=True)
def manage_devices(request):
    helper = DeviceFormSetHelper()
    title = "Manage all devices"
    if request.method == 'POST':
        formset = DeviceFormSet(request.POST, request.FILES, queryset=Device.objects.all())
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        formset = DeviceFormSet(queryset=Device.objects.all())
    cancel_url = reverse('index')
    return render(request, 'formset.html',
                  {'form': formset, 'helper': helper, 'cancel_url': cancel_url, 'title': title})

router-map/visualisation/views.py
from itertools import groupby

from crispy_forms.bootstrap import AppendedText
from crispy_forms.layout import Layout, Fieldset, HTML, Field
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from visualisation.models import Visualisation


@login_required
def visualisation_tree_view(request):
    return render(request, 'visualisation_tree_view.html',
                  {'visualisations': Visualisation.objects.filter(parent__isnull=True)})


def get_visualisation_layout():
    return Layout(
        HTML("<hr>"),
        Field('name'),
        HTML("<hr>"),
        Fieldset(
            'View',
            'display_link_descriptions',
            'links_default_width',
            'highlighted_links_width',
            AppendedText('highlighted_links_range_min', 'Gbit/s', active=True),
            AppendedText('highlighted_links_range_max', 'Gbit/s', active=True),
        ),
        Fieldset(
            'Tree view of visualisations',
            'parent'
        )
    )


def get_inactive_connections(all_links):
    list_inactive_connections = []
    all_links_values = all_links.values('local_interface__device', 'remote_interface__device', 'active',
                                        'local_interface__device__name', 'remote_interface__device__name') \
        .order_by('local_interface__device', 'remote_interface__device')

    grouped_by_devices = groupby(all_links_values, lambda x: (
        x.get('local_interface__device'), x.get('remote_interface__device')))

    for device_pair, group in grouped_by_devices:
        link_list_between_device_pair = list(group)
        active_links_number = sum([link.get('active') for link in link_list_between_device_pair])
        if active_links_number < len(link_list_between_device_pair):
            list_inactive_connections.append({
                "device1_pk": device_pair[0],
                "device2_pk": device_pair[1],
                "description": f"{link_list_between_device_pair[-1].get('local_interface__device__name')} - "
                               f"{link_list_between_device_pair[-1].get('remote_interface__device__name')}"
            })
    return list_inactive_connections

router-map/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="shortcut icon" href="{% static 'images/router.png' %}">
  <title>Router-map</title>
  {% block scripts %}
  {% endblock %}
</head>

<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">

  <div class="navbar-nav ml-auto">
    {% block navbar %}

    {% endblock %}
    <a class="nav-item nav-link" href="{% url 'account:logout' %}">
      Log out
    </a>
  </div>
</nav>
<div class="row main-row" style="margin: auto">
  <div class="container py-5">
    {% block content %}
    {% endblock %}
  </div>
</div>
</body>
</html>

router-map/templates/connection_detail.html
<h5 class="card-header sticky-top" id="card-left-header">
  <b>{{ connection.device1 }} - <br>{{ connection.device2 }}</b>
</h5>
<div class="card-body" id="card-left-body">
  <table class="table table-striped">
    <tbody>
    <tr>
      <td><b>Number of links</b></td>
      <td>{{ connection.number_of_links }}</td>
    </tr>
    <tr>
      <td><b>Number of active links</b></td>
      <td>{{ connection.number_of_active_links }}</td>
    </tr>
    <tr>
      <td><b>Speed of each link</b></td>
      <td>{{ connection.speed }}G</td>
    </tr>
    <tr>
      <td><b>Interface of router {{ connection.device1 }}</b></td>
      <td>{{ connection.interface1 }}</td>
    </tr>
    <tr>
      <td><b>Interface of router {{ connection.device2 }}</b></td>
      <td>{{ connection.interface2 }}</td>
    </tr>
    </tbody>
  </table>
  {% if perms.data.delete_link %}
    <button type="button" class="btn btn-secondary" id="delete_btn">Delete inactive links</button>
  {% endif %}
</div>

router-map/templates/device_detail.html
<h5 class="card-header sticky-top" id="card-left-header">
  <b>{{ device.name }}</b>
</h5>
<div class="card-body" id="card-left-body">
  <table class="table table-striped">
    <tbody>
    <tr>
      <td><b>Name</b></td>
      <td>{{ device.name }}</td>
    </tr>
    <tr>
      <td><b>IP address</b></td>
      <td>{{ device.ip_address }}</td>
    </tr>
    <tr>
      <td><b>Connection</b></td>
      <td>
        {% if device.connection_is_active %}
          active
        {% else %}
          inactive
        {% endif %}
      </td>
    </tr>
    </tbody>
  </table>
</div>

router-map/templates/diagram.html
{% extends "visualisation_base.html" %}
{% load staticfiles %}

{% block title %}
  <div class="navbar-brand" id="title" data-diagram-id={{ diagram.pk }}>
    {{ diagram.name }}
  </div>
{% endblock %}

{% block menu-options %}
  {% if perms.diagram.change_diagram %}
    <a href=# class="dropdown-item" id="save_position_btn">
      Save position of points
    </a>
    <a href="{% url 'diagram:update' diagram_pk=diagram.pk %}" class="dropdown-item">
      Edit diagram
    </a>
    <a href="{% url 'diagram:manage_devices' diagram_pk=diagram.pk %}" class="dropdown-item">
      Manage devices
    </a>
    <a href="{% url 'diagram:add_devices_via_csv' diagram_pk=diagram.pk %}" class="dropdown-item">
      Add devices via csv file
    </a>
  {% endif %}
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="{% static "js/bundle-diagram.js" %}"></script>
{% endblock %}

router-map/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block scripts %}
  <script type="text/javascript" src="{% static "js/bundle-base.js" %}"></script>
{% endblock %}

{% block content %}
  <h2>{{ title }}</h2>
  <form method="POST" enctype="multipart/form-data" id="update-form" class="form-horizontal" novalidate>
    {% csrf_token %}
    {% crispy form %}
    <div class="form-actions">
      <button type="submit" name="submit" class="btn btn-primary" id="submit">Save</button>
      <a href="{{ cancel_url }}" id="cancel" class="btn btn-danger">Cancel</a>
    </div>
  </form>
{% endblock %}

router-map/templates/form_new_visualisation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block scripts %}
  <script type="text/javascript" src="{% static "js/bundle-base.js" %}"></script>
{% endblock %}

{% block content %}
  <h2>{{ title }}</h2>
  <form method="POST" enctype="multipart/form-data" id="update-form" class="form-horizontal" novalidate>
    {% csrf_token %}
    {% crispy form %}
    <div class="form-actions">
      <button type="submit" name="to_add_manually" class="btn btn-primary" id="submit">
        Save and add devices manually
      </button>
      <button type="submit" name="to_add_via_csv" class="btn btn-primary" id="submit">
        Save and add devices via csv file
      </button>
      <a href="{{ cancel_url }}" id="cancel" class="btn btn-danger">
        Cancel
      </a>
    </div>
  </form>
{% endblock %}

router-map/templates/formset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block scripts %}
  <script type="text/javascript" src="{% static "js/bundle-formset.js" %}"></script>
{% endblock %}

{% block content %}
  <h2>{{ title }}</h2>
  <form method="POST" enctype="multipart/form-data" id="update-form" class="form-horizontal" novalidate>
    {% csrf_token %}
    {% crispy form helper %}
    <div class="form-actions">
      <button type="button" class="btn btn-secondary" id="add-more">Add one more</button>
      <div class="float-right">
        <button type="submit" name="submit" class="btn btn-primary" id="submit">Save</button>
        <a href="{{ cancel_url }}" id="cancel" class="btn btn-danger">Cancel</a>
      </div>
    </div>

  </form>
{% endblock %}

router-map/templates/inactive_connection_list.html
<h5 class="card-header sticky-top">
  <b class="align-middle">Inactive connections</b>
  <span class="float-right">
          <button class="btn btn-danger btn-sm" id="close_right_card_btn" style="color:white">
            Close
          </button>
        </span>
</h5>
<div class="card-body" id="card-right-body">
  <ul class="list-group" id="inactive_list">
    {% for connection in inactive_list %}
      <li class="list-group-item">
        {{ connection.description }}
      </li>
    {% endfor %}
  </ul>
</div>

router-map/templates/login.html
{% load crispy_forms_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="shortcut icon" href="{% static 'images/router.png' %}">
  <title>Router-map</title>
  <script type="text/javascript" src="{% static "js/bundle-base.js" %}"></script>
</head>

<body>
<div class="container-fluid d-flex min-vh-100">
  <div class="row bg-dark flex-fill justify-content-md-center">
    <div class="col-lg-4 my-auto">
      <div class="card mx-auto">
        <div class="card-body">
          <form method="POST" enctype="multipart/form-data" id="update-form" class="form-horizontal" novalidate>
            {% csrf_token %}
            {% crispy form %}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

router-map/templates/map.html
{% extends "visualisation_base.html" %}
{% load staticfiles %}

{% block title %}
  <div class="navbar-brand" id="title" data-map-id={{ map.pk }}>
    {{ map.name }}
  </div>
{% endblock %}

{% block menu-options %}
  {% if perms.map.change_map %}
    <a href="{% url 'map:update' map_pk=map.pk %}" class="dropdown-item">
      Edit map
    </a>
    <a href="{% url 'map:manage_devices' map_pk=map.pk %}" class="dropdown-item">
      Manage devices
    </a>
    <a href="{% url 'map:add_devices_via_csv' map_pk=map.pk %}" class="dropdown-item">
      Add devices via csv file
    </a>
  {% endif %}
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="{% static "js/bundle-map.js" %}"></script>
{% endblock %}

router-map/templates/tree_node.html
{% load tree_view %}
<li>
  {% if visualisation.children.all.exists %}
    <div class="list-group-item list-group-item-action d-flex align-items-center">
      <i class="caret caret-down"></i>
      <a href="{{ visualisation.get_absolute_url }}" class="ml-3">
        {{ visualisation.name }}
      </a>
    </div>
    <ul class="nested tree_view active">
      {% for child in visualisation.children.all %}
        {% tree_node child %}
      {% endfor %}
    </ul>
  {% else %}
    <div class="list-group-item list-group-item-action">
      <a href="{{ visualisation.get_absolute_url }}" class="ml-3 no-children">
        {{ visualisation.name }}
      </a>
    </div>
  {% endif %}
</li>

router-map/templates/visualisation_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="shortcut icon" href="{% static 'images/router.png' %}">
  <title>Router-map</title>
</head>
<style>
  .lds-dual-ring {
    position: absolute;
    left: 50%;
    top: 50%;
    display: inline-block;
    width: 120px;
    height: 120px;
  }

  .lds-dual-ring:after {
    content: " ";
    display: block;
    width: 104px;
    height: 104px;
    margin: 8px;
    border-radius: 50%;
    border: 6px solid #00c2c2;
    border-color: #00c2c2 transparent #00c2c2 transparent;
    animation: lds-dual-ring 1.2s linear infinite;
  }

  @keyframes lds-dual-ring {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }
</style>
<body>
<div id="loader">
  <div class="lds-dual-ring"></div>
</div>
<div style="display: none" id="page-content">
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    {% block title %}
    {% endblock %}
    <div class="navbar-nav ml-auto">
      <a class="nav-item nav-link" href="{% url 'index' %}">
        Visualisation list
      </a>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          Options
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href=# id="show_btn">Show list of inactive connections</a>
          {% block menu-options %}
          {% endblock %}
        </div>
      </li>
      <a class="nav-item nav-link" href="{% url 'account:logout' %}">
        Log out
      </a>
    </div>
  </nav>

  <div class="row main-row d-block" id='cards' style="margin: auto">
    <div class="col-sm-4 col-md-3 float-left">
      <div class="card" id="card-left" style="display:none;">
        <h5 class="card-header sticky-top" id="card-left-header"></h5>
        <div class="card-body" id="card-left-body"></div>
      </div>
    </div>
    <div class="col-sm-4 col-md-3 float-right">
      <div class="card" id="card-right" style="display:none">
      </div>
    </div>
  </div>
  <div class="footer bg-dark">
    <div class="text-light" id="data"></div>
  </div>

  <div class="modal fade" id="delete-modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-body" id="delete-modal-body">
          Are you sure you want to delete inactive links in chosen connection? Changes are not reversible.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="delete-modal-btn" data-dismiss="modal">Delete</button>
        </div>
      </div>
    </div>
  </div>
</div>

{% block scripts %}
{% endblock %}
</body>
</html>

router-map/templates/visualisation_tree_view.html
{% load staticfiles %}
{% load tree_view %}
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="shortcut icon" href="{% static 'images/router.png' %}">
  <title>Router-map</title>
  <script type="text/javascript" src="{% static "js/bundle-treeview.js" %}"></script>
</head>

<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">

  <div class="navbar-nav ml-auto">
    {% if perms.data.add_device and perms.data.change_device and perms.data.delete_device %}
      <a class="nav-item nav-link" href="{% url 'data:manage_devices' %}">
        Manage devices
      </a>
    {% endif %}
    {% if perms.diagram.add_diagram and perms.map.add_map %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          Add new visualisation
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'map:create' %}">Map</a>
          <a class="dropdown-item" href="{% url 'diagram:create' %}">Diagram</a>
        </div>
      </li>
    {% endif %}
    <a class="nav-item nav-link" href="{% url 'account:logout' %}">
      Log out
    </a>
  </div>
</nav>
<div class="row main-row" style="margin: auto">
  <div class="container py-5">
    <ul class="tree_view">
      {% for visualisation in visualisations %}
        {% tree_node visualisation %}
      {% endfor %}
    </ul>
  </div>
</div>